name: create-tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push new version tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Calculate current year and quarter
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          QUARTER=$(( ( (10#$MONTH - 1) / 3 ) + 1 ))
          
          # Get latest tag for current year
          LATEST_TAG=$(git tag --list "v${YEAR}.*" | sort -V | tail -n 1)
          
          # Determine build number
          if [ -z "$LATEST_TAG" ]; then
            BUILD=1
          else
            LATEST_TAG_NO_V="${LATEST_TAG#v}"
            LATEST_YEAR=$(echo $LATEST_TAG_NO_V | cut -d. -f1)
            LATEST_QUARTER=$(echo $LATEST_TAG_NO_V | cut -d. -f2)
            LATEST_BUILD=$(echo $LATEST_TAG_NO_V | cut -d. -f3)
            
            if [ "$LATEST_YEAR" = "$YEAR" ] && [ "$LATEST_QUARTER" = "$QUARTER" ]; then
              BUILD=$((LATEST_BUILD + 1))
            else
              BUILD=1
            fi
          fi
          
          # Create and push new tag
          NEW_VERSION_TAG="v${YEAR}.${QUARTER}.${BUILD}"
          echo "Creating tag: ${NEW_VERSION_TAG}"
          git tag "${NEW_VERSION_TAG}"
          git push origin "${NEW_VERSION_TAG}"